ubiquo_core/config/routes.rb
Ubiquo::Engine.routes.draw do
  get "" => "home#index", :as => :home
  get "attachment/*path" => "attachment#show", :format => false, :as => :attachment
  resources :ubiquo_settings
end

ubiquo_core/app/models/setting.rb
class Setting < ActiveRecord::Base

  serialize :value
  serialize :options
  serialize :allowed_values
  validates_presence_of :context
  validates_presence_of :type
  # don't work as expected, probably because of the getters
  #validates_uniqueness_of :key, :scope => [:context]
  validate :override_enabled?
  validate :check_is_editable
  validate :check_config_existence
  validate :check_config_value_same
  validate :check_config_acceptance
  validate :check_config_value_acceptance

 #before_validation :try_setting_type
  before_validation :set_default_context
  before_validation :stringify_fields

  after_save :apply
  after_destroy :push_config

  # Check if the value is included in the alloweds
  def value_acceptable?
    self.allowed_values.blank? ||
      self.allowed_values.include?(self.value)
  end
  
  # Check if the context of the setting exists
  def context_exists?
    Ubiquo::Settings.context_exists?(self.context)
  end

  # Check is a setting is allowed to have a nil value
  def nullabe?
    context_exists? &&
    config_exists? &&
    Ubiquo::Settings[self.context].nullable?(self.key)
  end

  # Check if a setting exists
  def config_exists?
    context_exists? &&
    Ubiquo::Settings[self.context].option_exists?(self.key).present?
  end

  def config_editable?
    config_exists? &&
    Ubiquo::Settings[self.context].editable?(self.key).present?
  end
  
  def config_value_same?
    uhook_config_value_same?
  end

  def check_config_acceptance
    self.errors.add :value, 'value is not included in the alloweds' if !value_acceptable?
  end
  
  def check_config_value_same
    self.errors.add :value, 'cannot override a value with the same' if config_value_same?
  end

  def check_config_value_acceptance
    if self.class.respond_to?(:check_values) &&
        !self.class.check_values(Array(self.value))
      self.errors.add :value, "#{self.value} is not allowed"
    end
  end

  # Validate a setting
  def check_config_existence
    self.errors.add :value, 'not nullable' if  self.value.nil?  && !nullabe?
    self.errors.add :key, 'invented setting FTW!' if !config_exists?
    self.errors.add :context, 'invited context' if !context_exists?
  end

  def override_enabled?
    self.class.override_enabled?
  end
  
  # Check if overriden settings are enabled
  def self.override_enabled?
    Ubiquo::Settings.overridable?
  end

  # Tries to enable a specific setting 
  def apply 
    Ubiquo::Settings[self.context].add(self)
  end

  def self.find_or_build context, setting_key, options = {}
    uhook_find_or_build context.to_sym, setting_key.to_sym, options
  end

  def push_config
    self.class.push_config
  end
    
  # Tries to load and enable all overriden setting from db
  def self.push_config
    Ubiquo::Settings.load_from_backend!
  end

  def check_is_editable
    self.errors.add :key, 'not editable' if !self.config_editable?
  end

  # Validates uniqueness of the key
  def validate_key_uniqueness
    self.errors.add :key if Setting.find_by_context_and_key(self[:context], self[:key]).present?
  end

  # Set the defaul context for the setting
  def set_default_context
    self.context = Ubiquo::Settings.default_context if self.context.blank?
  end

  # Prepare context and key properties to storage as a string
  def stringify_fields
    self[:context] =  self[:context].to_s if self[:context].present?
    self[:key] = self[:key].to_s if self[:key].present?
  end
 
  # Accessor, format the key to a symbol
  def key
    self[:key].to_sym if self[:key].present?
  end

  # Accessor, format the context to a symbol
  def context
    self[:context].to_sym if self[:context].present?
  end

  def try_setting_type
    self.type = generate_type(self.context, self.key) if !self.type
    self.type = nil if self.type == Setting
  end

  def self.generate_type context, key
    value = Ubiquo::Settings[context.to_sym].get(key.to_sym, :any_value => true)
    return PasswordSetting if value.class == String && Ubiquo::Settings[context.to_sym].options(key.to_sym)[:is_password]
    return BooleanSetting if value == true || value == false
    return IntegerSetting if value.class == Fixnum
    "#{value.class}Setting".constantize rescue Setting
  end
  
  def generated_from_another_value?
    uhook_generated_from_another_value?
  end

#  def to_s
#   "#{key}:#{value}"
# end
end

ubiquo_core/app/controllers/ubiquo/attachment_controller.rb
class Ubiquo::AttachmentController < UbiquoController
  def show
    send_multimedia(params[:path], :x_sendfile => Ubiquo::Settings.get(:attachments)[:use_x_send_file])
  end

  protected

  def send_multimedia(requested_path, options = {})
    protected_path = Rails.root.join(Ubiquo::Settings.get(:attachments)[:private_path])
    absolute_path = File.expand_path(File.join(protected_path, requested_path))
    # TODO: Look for a better way to do this. Here we need to make sure that we only 
    # serve assets that belong to the protected_path to avoid security issues 
    # (using a regexp against the expanded path).
    unless absolute_path && File.exists?(absolute_path) && absolute_path =~ /^#{protected_path}/
      raise ActiveRecord::RecordNotFound 
    end
    
    filename = File.basename(absolute_path)
    case File.extname(filename).downcase
      when ".jpg", ".jpeg"
        content_type = "image/jpeg"
        disposition = "inline"
        send_data open(absolute_path, "rb").read, { :filename    => filename,
                                                    :type        => content_type,
                                                    :disposition => disposition }.merge(options)
        return
      when ".png"
        content_type = "image/png"
        disposition = "inline"
        send_data open(absolute_path, "rb").read, { :filename    => filename,
                                                    :type        => content_type,
                                                    :disposition => disposition }.merge(options)
        return
      when ".gif"
        content_type = "image/gif"
        disposition = "inline"
        send_data open(absolute_path, "rb").read, { :filename    => filename,
                                                    :type        => content_type,
                                                    :disposition => disposition }.merge(options)
        return
      when ".mp3"
        content_type = "audio/mpeg"
        disposition = "inline"
        send_data open(absolute_path, "rb").read, { :filename    => filename,
                                                    :type        => content_type,
                                                    :disposition => disposition }.merge(options)
        return
      when ".wmv"
        content_type = "video/x-ms-wmv"
        disposition = "attachment"
      when ".avi"
        content_type = "video/avi"
        disposition = "attachment"
      when ".mov"
        content_type = "video/quicktime"
        disposition = "attachment"
      when ".mp4"
        content_type = "video/mp4"
        disposition = "attachment"
      when ".mpg"
        content_type = "video/mpeg"
        disposition = "attachment"
      when ".flv"
        content_type = "video/x-flv"
        disposition = "attachment"
      when ".zip"
        content_type = "application/zip"
        disposition = "attachment"
      else
        content_type = "application/octet-stream"
        disposition = "attachment"
    end

    response.headers["Content-type"] = content_type
    response.headers['Content-length'] = File.size(absolute_path)
    response.headers['Cache-Control'] = 'must-revalidate'

    send_file absolute_path, { :filename    => filename,
                               :type        => content_type,
                               :disposition => disposition }.merge(options)
  end
end

ubiquo_core/app/controllers/ubiquo/ubiquo_settings_controller.rb
class Ubiquo::UbiquoSettingsController < UbiquoController

  ubiquo_config_call :settings_access_control
  before_filter :clean_result

  # GET /settings
  # GET /settings.xml
  # GET /settings.json
  def index
    find_settings
    respond_to do |format|
      format.html # index.html.erb
      format.xml  {
        render :xml => @contexts
      }
    end
  end

  def destroy
    @ubiquo_setting = UbiquoSetting.find(params[:id])
    if @ubiquo_setting.destroy
      flash[:notice] = t("ubiquo.ubiquo_setting.destroyed",
                        :key => @ubiquo_setting.key,
                        :context => @ubiquo_setting.context)
    else
      flash[:error] = t("ubiquo.ubiquo_setting.destroy_error")
    end
    respond_to do |format|
      format.html { redirect_to(ubiquo.ubiquo_settings_url) }
      format.xml  { head :ok }
    end
  end

  # POST /settings
  # POST /settings.xml
  def create
    result = @result = uhook_create_ubiquo_setting
    respond_to do |format|
      if result[:errors].present?
        flash[:error] = result[:errors].length == 1 ?
          "1 #{t("ubiquo.ubiquo_setting.error")}" :
          "#{result[:errors].length} #{t("ubiquo.ubiquo_setting.errors")}"
      end
      notice_message = nil
      if result[:valids].present?
        notice_message = result[:valids].length == 1 ?
          "1 #{t("ubiquo.ubiquo_setting.created")}" :
          "#{result[:valids].length} #{t("ubiquo.ubiquo_setting.createds")}"
      end

      if result[:errors].present?
        flash[:error] = [notice_message, flash[:error]].compact.join(' - ')
      else
        flash[:notice] = notice_message
      end

      if result[:valids].present?
        format.xml  { render :xml => @ubiquo_setting, :status => :created, :location => @ubiquo_setting }
      elsif result[:errors].present?
        format.xml  { render :xml => result[:errors], :status => :unprocessable_entity }
      end

      format.html {
        find_settings
        render :action => :index
      }
    end
    @result = nil
  end

  private

  def find_settings
    @contexts = Ubiquo::Settings.overridable? ? uhook_index : {}
  end

  def load_setting
    @ubiquo_setting = UbiquoSetting.find(params[:id])
  end

  def clean_result
    @result = nil
  end
end

ubiquo_core/app/helpers/ubiquo/ubiquo_settings_helper.rb
module Ubiquo::UbiquoSettingsHelper

  def ubiquo_setting_filters
    uhook_setting_filters
  end

  def ubiquo_setting_list(contexts, form, options = {})
    form.group(:type => :tabbed) do
      contexts.map do |context, setting_keys|
        content_tag(:div, :id => "context_#{context}", :class => 'context') do
          form.tab UbiquoSetting.context_translated(context) do
            context_data(context, setting_keys)
          end
        end
      end.join.html_safe
    end + submit_all_button
  end

  private

  def context_data(context, setting_keys)
    each_setting_key(context, setting_keys) do |ubiquo_setting|
      content_tag(:div, :class => "form-item") do
        setting_info(ubiquo_setting) +
        setting_actions(ubiquo_setting)
      end
    end.join.html_safe
  end

  def submit_all_button
    content_tag(:div, :class => "form-item-submit") do
      submit_tag(t('ubiquo.ubiquo_setting.index.save_all'),
                  :onclick => javascript_callback,
                  :class => 'save_all')
    end
  end

  def javascript_callback
    "return collectAndSendValues();return false;"
  end

  def setting_info(ubiquo_setting)
    content_tag(:div, :class => "setting-info") do
      print_key_label(ubiquo_setting) +
      render_value(ubiquo_setting)
    end
  end

  def setting_actions(ubiquo_setting)
    content_tag(:div, :class => "setting-actions") do
      content_tag(:ul, :class => "actions") do
        uhook_ubiquo_setting_index_actions(ubiquo_setting).map do |action|
          content_tag(:li, action)
        end
      end
    end
  end

  def each_setting_key(context, setting_keys, &block)
    settings = setting_keys.map do |setting_key|
      get_ubiquo_setting(context, setting_key)
    end
    settings.map {|setting| yield(setting)}
  end

  def render_empty_list_message
    render(:partial => "shared/ubiquo/lists/empty", :locals => {
        :model => UbiquoSetting,
        :name => 'ubiquo_setting',
        :link_to_new => ''
    })
  end

  def render_template_type ubiquo_setting
    type = ubiquo_setting.class.name.gsub('Setting', '').gsub('Ubiquo', '').underscore
    type = UbiquoSetting.name.underscore if type.blank?

    result = render(:partial => "/ubiquo/ubiquo_settings/#{ubiquo_setting.context}/#{ubiquo_setting.key}",
                        :locals => { :ubiquo_setting => ubiquo_setting }) rescue false
    result = render(:partial => "/ubiquo/ubiquo_settings/#{type}",
                        :locals => { :ubiquo_setting => ubiquo_setting }) rescue false if !result
    result = render(:partial => "/ubiquo/ubiquo_settings/ubiquo_setting.html.erb",
                      :locals => { :ubiquo_setting => ubiquo_setting }) if !result
    result
  end

  def render_value ubiquo_setting
    render :partial => 'form', :locals => {:ubiquo_setting => ubiquo_setting}, :class => 'setting'
  end

  def get_ubiquo_setting(context, ubiquo_setting_key)
    add_errors uhook_get_ubiquo_setting(context, ubiquo_setting_key)
  end

  def add_errors ubiquo_setting
    error_dump = self.controller.instance_variable_get(:@result)[:errors] rescue []
    error_object = error_dump.find do |e|
      e.present? &&
      e.context == ubiquo_setting.context &&
        e.key == ubiquo_setting.key
    end
    if error_object.present? && ubiquo_setting.errors.blank?
      ubiquo_setting = error_object
    end
    ubiquo_setting
  end

  def print_key_label ubiquo_setting
    uhook_print_key_label ubiquo_setting
  end

  def setting_dom_id ubiquo_setting
    [ubiquo_setting.context, "ubiquo_setting", ubiquo_setting.key].join('_')
  end

  def error_class ubiquo_setting
    ubiquo_setting.errors.present? ? " error_field" : " "
  end

  def restore_link ubiquo_setting
    restore_text = t('ubiquo.ubiquo_setting.index.restore_default')
    restore_url  = ubiquo.ubiquo_setting_path(ubiquo_setting)
    confirm_text = t('ubiquo.ubiquo_setting.index.confirm_restore_default')

    link_to(
      restore_text,
      restore_url,
      :data => {:confirm => confirm_text},
      :method  => :delete,
      :class   => 'btn-restore'
    )
  end

end

ubiquo_core/app/views/ubiquo/settings/index.html.erb
<style type="text/css">
  #contexts table td:first-child{
    width:20%;
  }
  .context-header{
     font-size: 1.2em;
     font-weight: bolder;
      background:#ECF5F4;
  }
  #contexts form{
    padding:0;
  }
  #contexts .form-item {
    margin:0;
  }
  #contexts .form-item fieldset{
    margin:0.1em 0.1em 0.1em 0.1em;
    padding:0;
  }  
  #contexts .form-item .number{
    background:#F0BB47;
    width:15%;
  }
  #contexts tr:hover{
    background:inherit;
  }
  #contexts form{
    border: 0;
  }
  #contexts form input, #contexts form textarea, #contexts form select{
    padding: 0.1em;
  }
  
  #contexts textarea, #contexts input{
    width: 100% !important;
  }
  #bulk_submit input{
    margin-left:90%;    
  }
  #contexts .translatable{
    
  }
  

</style>
<h1>
  <%= render :partial => 'title' %>
</h1>

<h2>
  <%= render :partial => 'submenu' %>
</h2>

<%= render :partial => "shared/ubiquo/feedback" %>

<% # = show_filter_info
%>

<div id="contexts">
  <% @contexts.each do |context, settings| %>
    <h3 class="context-header"><%= translate_context_name(context) %></h3>
    <%= setting_list(context, settings) %>
  <% end %>
</div>

<% javascript_tag do -%>
  function collectAndSendValues(selectedContext, selectedSettingKey){
    var settings = {}
    var contexts = $$('#contexts > table');
    for(var i = 0; i < contexts.length; ++i){
      var contextKey = $(contexts[i]).readAttribute('id')
      if(selectedContext == null || contextKey == selectedContext ){
        settings[contextKey] = {}
        var settingsRows = $(contexts[i]).getElementsBySelector('tbody tr');
        for(var j = 0; j < settingsRows.length; ++j){
          var settingKey = settingsRows[j].readAttribute('id');          
          settingKey = settingKey.replace('setting_','');
          if(selectedSettingKey == null || settingKey == selectedSettingKey){        
              
            var settingValue;
            // Is a select 
            if(settingsRows[j].getElementsBySelector('input[name="' + settingKey + '"]').length == 0 &&
                settingsRows[j].getElementsBySelector('select[name="' + settingKey + '"]').length){
              settingValue = settingsRows[j].getElementsBySelector('select[name="' + settingKey + '"]').first().value;  
            }
            // Is a textarea
            else if(settingsRows[j].getElementsBySelector('textarea[name="' + settingKey + '"]').length){
              settingValue = settingsRows[j].getElementsBySelector('textarea[name="' + settingKey + '"]').first().value;  
            }
            // Is a input
            else {    
              settingValue = settingsRows[j].getElementsBySelector('input[name="' + settingKey + '"]').first().value;
              // Is a checkbox
              if(settingsRows[j].getElementsBySelector('input[name="' + settingKey + '"]').first().type == 'checkbox'
                 && settingsRows[j].getElementsBySelector('input[name="' + settingKey + '"]').first().checked == false){
                settingValue = false;
              }     
              // Is a password
              if(settingsRows[j].getElementsBySelector('input[name="' + settingKey + '"]').first().type == 'password'
                 && settingsRows[j].getElementsBySelector('input[name="confirmation_' + settingKey + '"]').length){

                var confirmationKey = "confirmation_" + settingKey
                var confirmationValue = settingsRows[j].getElementsBySelector('input[name="confirmation_' + settingKey + '"]').first().value
                settings[contextKey][confirmationKey] = confirmationValue;
              }                   
            }
            settings[contextKey][settingKey] = settingValue;
          }
        }
      }
    }
    var form = $('bulk_submit');
    for(var context in settings) {
      for(var settingKey in settings[context]) {
        var hiddenField = document.createElement("input");
        hiddenField.setAttribute("type", "hidden");
        hiddenField.setAttribute("name", "settings" + "[" + context + "[" + settingKey + "] ]");
        hiddenField.setAttribute("value", settings[context][settingKey]);

        $(form).appendChild(hiddenField);
      }
    }
    form.submit();
  }
<% end %>


<% form_tag ubiquo_settings_path, {:onSubmit  => "return collectAndSendValues();", 
                                    :id => "bulk_submit"} do %>
  <%= submit_tag t('ubiquo.setting.index.save_all')  %>
<% end %>

<% content_for :sidebar do %>
  <%# show_filters %>
  <%# help_block_sidebar t("ubiquo.setting.index.help_message") %>
<% end %>